name: rl-for-csps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - gym
    - transformers
    - datasets
    - huggingface_hub
    - accelerate
    - "stable-baselines3[extra]>=2.0.0a4"
